[package]
name = "lab"
version = "0.1.0"
edition = "2021"

[dependencies]
dimension = { path = "../dimension" }
compare = { path = "../compare" }
dev_tests = { path = "../dev_tests" }
array_maker = { path = "../array_maker" }
expression = { path = "../expression" }
